apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orderstore
spec:
  type: state.postgresql
  version: v2
  metadata:
    - name: connectionString
      value: "host=localhost port=5432 user=postgres password=postgres dbname=orderingdb"
scopes:
  - ordering
