apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: shopstate
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis_service:6379
  - name: redisPassword
    value: ""
